### ISSUE TITLE
failing on dataframe column name being an ndarray

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/ott-utils#2]
Under certain versions of netCDF4, this error occurs indicating that the `units` parameter is being set to an ndarray instead of a string or dict:

```
Traceback (most recent call last):
  File "classsummary2netcdf.py", line 40, in <module>
    process_dir(in_dir, out_dir)
  File "classsummary2netcdf.py", line 34, in process_dir
    csdir2netcdf(in_dir, out_dir, frequency=freq, threshold=thresh, metadata=md)
  File "/ifcb_code/ott-utils/ott/netcdf.py", line 77, in csdir2netcdf
    cs2netcdf(cs_path, nc_path, frequency=frequency, threshold=threshold, metadata=metadata)
  File "/ifcb_code/ott-utils/ott/netcdf.py", line 65, in cs2netcdf
    instrument_attributes=i_attrs)
  File "netcdf-cf-utils/nccf/timeseries.py", line 66, in from_dataframe
    self.create_obs_vars(df, ('timeseries','time'), units)
  File "netcdf-cf-utils/nccf/cf.py", line 122, in create_obs_vars
    u = units if type(units) is str else units.get(varname)
TypeError: unhashable type: 'numpy.ndarray'

Software package versions:
numpy v1.12.0
munch v2.1.0
scipy v0.18.1
pandas v0.19.2
netCDF4 v 1.0
yaml v3.10
```

**Comment by joefutrelle** [comment]
Not sure if this is a bug in `ott-utils` or `netcdf-cf-utils`

**Comment by joefutrelle** [comment]
The column names for the dataframe being passed in to `create_obs_vars` are read from the data structure returned by `scipy.io.loadmat` in `ClassSummary`, and if in some version of scipy those are ndarrays of chars instead of strings, could be the cause of this error.

**Comment by joefutrelle** [comment]
Still baffled as to what causes this, but coercing the column names to be strings should work.

**Comment by joefutrelle** [comment]
Cannot reproduce, even with these package versions.
